81 - Adicionar Filtros de Movimentação
fga-eps-mds/2023-1-Alectrion-FrontEnd pull request #12
Opened 2023-05-25 03:41 UTC by JPedroCh

## Modificações
 Adição de filtros para listagem de movimentações.
## Descrição
  - Integração dos filtros de movimentação com o backend
  - Ajuste no componente de controlled select para ser possível o teste.
## _Issue_ relacionado
 81
## Como foi testado?
   - Foi escrito teste para tela de movimentações

## Lista de controle:
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meu _commits_ segue a política de commits do repo.
- [ ] Adicionei testes para cobrir minhas modificações.

2023-05-25 04:52 UTC, DafneM approved these changes
Show!

2023-05-25 20:54 UTC, AlineLermen approved these changes

2023-05-26 13:01 UTC, AlineLermen requested changes

2023-05-26 13:01 UTC, AlineLermen commented on src/config/lib/axios/index.ts
> +  baseURL: 'http://localhost:4000/',
Favor voltar para url do deploy
```suggestion
  baseURL: 'https://alectrion-gateway-2023.herokuapp.com/',
```

2023-05-26 13:01 UTC, AlineLermen commented on src/config/lib/axios/index.ts
> +});
Aqui acredito que não seja necessário essas duas URLs, certo? Seria mais uma questão de adaptação onde elas estão sendo chamadas. Aí é uma escolha de manter a URL base ou a URL já com o endpoint `/workstations`

2023-05-26 13:11 UTC, AlineLermen reviewed
Uma observação, que talvez fosse interessante alterar é que sejam incluídas as movimentações da data final selecionada.

* Atualmente, se a data final selecionada é 26/05/2023, aparece somente as movimentações até o dia 25/05/2023. Acredito que deveria aparecer do dia 26 também
* A data inicial está correta. Se seleciono 01/05/2023, ele inclui as movimentações dessa data.

2023-05-26 15:12 UTC, JPedroCh commented
> Uma observação, que talvez fosse interessante alterar é que sejam incluídas as movimentações da data final selecionada.
> 
> * Atualmente, se a data final selecionada é 26/05/2023, aparece somente as movimentações até o dia 25/05/2023. Acredito que deveria aparecer do dia 26 também
> * A data inicial está correta. Se seleciono 01/05/2023, ele inclui as movimentações dessa data.

A solução foi implementada na API de equipamentos. Também foi solucionado um bug de apresentação da data na listagem diferente da recebida pela requisição, era necessário especificar a timezone.

2023-05-26 18:19 UTC, AlineLermen approved these changes

2023-05-26 18:25 UTC, merged