#107 fix: adiciona modal de movimentacao a partir da tela de equipame…
fga-eps-mds/2023-1-Alectrion-FrontEnd pull request #24
Opened 2023-05-31 03:02 UTC by DafneM

## Descrição

Este PR corrige o problema de quando clica na modal não aparecer para criar uma movimentação relacionada aos equipamentos.

2023-05-31 03:36 UTC, JPedroCh requested changes
É preciso ajustar para que a modal de visualizar equipamento não abra ao clicar na checkbox. Além disso, tá redundante o usuário selecionar 2 vezes quais equipamentos deseja incluir na movimentação.

2023-05-31 10:25 UTC, AlineLermen reviewed
Será mantida a opção de movimentação tanto pela tela de equipamentos quanto pelo botão "Cadastrar Movimentação" na tela de movimentações, certo?

Concordo com as mudanças pedidas pelo João, além de que o lint não está passando. Assim que feitas, reviso novamente

2023-06-04 15:56 UTC, lucasgbezerra commented
As modificações solicitas foram realizadas, assim como a adição de um toast para erro.

2023-06-04 16:20 UTC, JPedroCh approved these changes
LGTM!

2023-06-05 00:26 UTC, AlineLermen approved these changes

2023-06-05 02:58 UTC, merged