#56 feat adiciona termo de baixa
fga-eps-mds/2023-1-Alectrion-FrontEnd pull request #36
Opened 2023-06-07 16:08 UTC by DafneM

## Descrição

O objetivo deste PR é adicionar o termo de baixa.

2023-06-07 19:12 UTC, JPedroCh requested changes

2023-06-07 19:12 UTC, JPedroCh commented on src/components/movements-pdf/MovementsPdfDocument.tsx
> +              26ª DELEGACIA DE POLÍCIA DE GOIÂNIA
Esse campo (linha 219) deve ser realmente hardcoded?

2023-06-14 00:22 UTC, DafneM commented on src/components/movements-pdf/MovementsPdfDocument.tsx
> +              26ª DELEGACIA DE POLÍCIA DE GOIÂNIA
@JPedroCh corrigido, pode dar uma olhada?

2023-06-14 00:32 UTC, linktocaio approved these changes
LGTM : )

2023-06-14 01:13 UTC, JPedroCh approved these changes
LGTM

2023-06-14 01:17 UTC, merged