101 cadastro ordem servico
fga-eps-mds/2023-1-Alectrion-FrontEnd pull request #37
Opened 2023-06-07 16:08 UTC by pedroyen21

## Modificações
- Adição de modal de cadastro de ordem de serviço.

## Issue relacionado
[101](https://github.com/fga-eps-mds/2023-1-Alectrion-DOC/issues/101)

2023-06-07 17:08 UTC, JPedroCh commented
É necessário fazer um ajuste de maneira que o usuário não tenha que fazer essa adição no token. Uma opção seria fazer esse set no localStorage direto no código mesmo que hardCoded.

2023-06-12 22:46 UTC, JPedroCh commented
O lint está quebrando.

2023-06-14 04:14 UTC, JPedroCh requested changes
O Select de número de tombamento começa apresentando nenhuma opção.

2023-06-14 04:15 UTC, JPedroCh commented on src/components/order-service-register-form/index.tsx
> +            placeholder="username"
Alterar placeholder para "Nome de usuário"

2023-06-21 12:57 UTC, JPedroCh approved these changes
LGTM

2023-06-21 15:06 UTC, luanatorress commented
O select ainda só busca opções após iniciar digitação. Retirar os console.log do código se não necessário. De resto tudo ótimo.

2023-06-21 15:07 UTC, luanatorress reviewed
O select ainda só busca opções após iniciar digitação. Retirar os console.log do código se não necessário. De resto tudo ótimo.

2023-06-21 18:19 UTC, esteerlino approved these changes

2023-06-21 18:19 UTC, merged