#125 FIX: Componente de Controlled Select
fga-eps-mds/2023-1-Alectrion-FrontEnd pull request #39
Opened 2023-06-08 21:46 UTC by JPedroCh

## Modificações
Este PR contem a criação de um novo componente de controlled select com o intuito de remover a dependência da biblioteca chakra-react-select e possibilitar os testes.
  
## _Issue_ relacionado 
 [125](https://github.com/fga-eps-mds/2023-1-Alectrion-DOC/issues/125)

## Lista de controle:
- [X] Meu código segue a folha de estilos implementada
- [X] Meu _commits_ segue a política de commits do repo.
- [X] Adicionei testes para cobrir minhas modificações.

2023-06-13 19:43 UTC, lucasgbezerra commented on src/config/lib/axios/index.ts
> +  baseURL: 'http://localhost:4000/',
Você poderia alterar para o endereço: https://alectrion-gateway-2023.herokuapp.com/

2023-06-13 19:54 UTC, lucasgbezerra reviewed
A borda de quando controlledSelect esta na cor azul, para manter o componente condizente com o guia de estilo, é preciso modificar.

Por favor, Utilize a cor primária

2023-06-14 00:04 UTC, DafneM requested changes
Os filtros de localização e situação de equipamento estão quebrando, quando colocamos algum deles, não aparece o botão de limpar!

2023-06-14 00:20 UTC, lucasgbezerra approved these changes
LGTM

2023-06-14 00:23 UTC, DafneM approved these changes
Show!

2023-06-14 00:29 UTC, suzaneduarte commented on package.json
> +    "@testing-library/user-event": "^14.4.3",
Bibliotecas de teste não deveriam ser incluídas no `dependencies`, e sim no `devDependencies` já que é uma biblioteca utilizada somente durante o desenvolvimento.

2023-06-14 00:29 UTC, suzaneduarte commented on src/components/movement-form/index.tsx
> +  console.log('selectedUnit => ', selectedUnit);
Esse console é realmente necessário?

2023-06-14 00:29 UTC, suzaneduarte commented on src/components/movement-form/index.tsx
> +      console.log(data);
Esse console é realmente necessário?

2023-06-14 00:29 UTC, suzaneduarte commented on src/components/movement-form/index.tsx
> +              label: unit?.name !== undefined ? unit?.name : '',
O que você acha de:

```suggestion
              value: unit?.id ?? '',
              label: unit?.name ?? '',
```

2023-06-14 00:36 UTC, JPedroCh commented on src/components/movement-form/index.tsx
> +              label: unit?.name !== undefined ? unit?.name : '',
Muito legal a sugestão!

2023-06-14 00:36 UTC, JPedroCh commented on src/components/movement-form/index.tsx
> +      console.log(data);
Corrigido

2023-06-14 00:36 UTC, JPedroCh commented on src/components/movement-form/index.tsx
> +  console.log('selectedUnit => ', selectedUnit);
Corrigido

2023-06-14 00:43 UTC, suzaneduarte approved these changes
Adicionei só mais um ponto sobre a biblioteca `'@testing-library/react-hooks'`, mas fora isso, ótimo trabalho!

2023-06-14 00:43 UTC, suzaneduarte commented on package.json
> +    "@testing-library/react-hooks": "^8.0.1",
Acredito que não tem necessidade de utilizar essa biblioteca, visto que ela foi incorporada na biblioteca @testing-library/react [desde da versão 13.1.0](https://github.com/testing-library/react-hooks-testing-library#details)

2023-06-14 00:43 UTC, suzaneduarte commented on src/components/form-fields/new-controlled-select/new-controlled-select.spec.tsx
> +import { renderHook } from '@testing-library/react-hooks';
```suggestion
import { render, screen, renderHook } from '@testing-library/react';
```

2023-06-14 00:45 UTC, suzaneduarte commented on package.json
> +    "@testing-library/react-hooks": "^8.0.1",
https://github.com/testing-library/react-testing-library/releases/tag/v13.1.0

2023-06-14 00:55 UTC, merged