130 fix: pegando a quantidade correta de equipamentos
fga-eps-mds/2023-1-Alectrion-FrontEnd pull request #43
Opened 2023-06-14 22:46 UTC by mibasFerraz

## Modificações
* Corrige a quantidade de equipamentos selecionados na modal, agora não está mais hard coded

## Issue Relacionada
130

2023-06-16 18:15 UTC, JPedroCh commented
O lint tá quebrando

2023-06-20 23:12 UTC, AlineLermen requested changes
O total de equipamentos não está atualizando ao mudar a seleção de equipamentos.

Para reproduzir:
"Movimentações" -> "Cadastrar Movimentação" -> selecionar algum equipamento

2023-06-21 00:46 UTC, JPedroCh approved these changes
LGTM

2023-06-21 23:03 UTC, AlineLermen approved these changes

2023-06-21 23:03 UTC, merged