149 fix senhas usuarios
fga-eps-mds/2023-1-Alectrion-FrontEnd pull request #56
Opened 2023-07-03 02:47 UTC by pedroyen21

## Modificações
Modificações propostas na issue 149

## Descrição
 - Quando o usuário for cadastrado com perfil de consulta, o administrador  informa uma senha e esse usuário não poderá alterá-la;

- A aplicação agora suporta login com cpf;

- Quando for cadastrar usuário como admin ou básico, não  tem o campo de senha, é gerada uma senha temporaria e mandada por email;

- Quando um usuário com status de senha temporária for logar, ele vai para a página de alteração de senha;

- A tela de recuperação de senha tem a logo da alectrion;

- O usuário não  consegue cadastrar qualquer coisa no email;

- Apenas admins conseguem criar, deletar, alterar outros usuários;

## _Issue_ relacionado
149

## Como foi testado?
Testes manuais

## Lista de controle:
- [x] Meu _commits_ segue a política de commits do repo.

2023-07-03 22:14 UTC, JPedroCh commented
Tá sendo possível cadastrar usuário do tipo consulta sem senha, além disso ao tentar cadastrar um usuário com username repetido, aparece o toast de erro, porém o botão de cadastrar fica no modo loading mesmo após retorno da API.

2023-07-03 22:26 UTC, JPedroCh commented
Para o tipo de usuário "Consulta", está aparecendo a opção de alterar senha na tela de visualizar perfil, por mais que não seja possível alterar pela validação da API, acredito que seja melhor verificar o tipo de usuário na tela de visualizar perfil e caso seja do tipo Consulta, não apresentar o botão "Alterar senha"

2023-07-03 22:33 UTC, JPedroCh commented
Ao criar um usuário do tipo Admin e fazer o primeiro login com a senha temporário, o usuário é redirecionado para tela de alterar senha, porém após alterar a senha não é redirecionado para nenhuma página e ao clicar no botão "Voltar", é redirecionado para o login.

Para a experiência do usuário seria melhor redirecionar o usuário para a home após alterar a senha temporária.

2023-07-03 22:39 UTC, JPedroCh requested changes
As solicitações de mudanças foram feitas nos comentários.

2023-07-04 00:27 UTC, pedroyen21 commented
Obrigado João, eu não tinha percebido que um  usuário de consulta conseguia ser cadastrado sem senha e consertei isso no back. Tá funcionando porque agora surge um toast de erro, mas não consegui fazer essa validação no front. 
Acho que consegui consertar as outras coisas.

2023-07-04 02:55 UTC, JPedroCh approved these changes
LGTM

2023-07-04 02:55 UTC, JPedroCh commented
Só faltar corrigir o teste que está quebrando

2023-07-05 22:57 UTC, JoaoVitorFarias approved these changes
OK!

2023-07-07 02:19 UTC, merged