150 - Criar múltiplos equipamentos
fga-eps-mds/2023-1-Alectrion-FrontEnd pull request #58
Opened 2023-07-04 11:00 UTC by suzaneduarte

## Modificações
O botão ```Adicionar arquivo XLS``` foi adicionado na modal de Cadastro de Equipamentos. Através dele, é possível anexar uma planilha Excel para que vários equipamentos sejam cadastrados de uma única vez. 

## Descrição

- Em ```src/components/equipment-register-modal/index.tsx``` foi adicionado o botão para abrir a modal de Upload de arquivo XLS. 

- Em ```src/components/equipment-upload-modal/index.tsx``` foi criada a modal para que seja possível realizar o anexo do Excel. Na modal, é possível enviar o arquivo tanto arrastando-o até o quadrado pontilhado, ou através do botão Escolher arquivo

## Issue relacionado
150

## Como foi testado?
- O teste é realizado manualmente através do uso de uma planilha Excel, a qual é disponibilizada em [Planilha De Teste XLS](https://docs.google.com/spreadsheets/d/13irOzM9XgE3xKnnh3M3mQbgott5P16aS/edit#gid=1429904599)

- Para que seja possível realizar o teste de maneira adequada, é necessário subir o repositório ```2023-1-Alectrion-EquipamentApi```

- Além disso, também é necessário que o docker esteja atualizado. Para isso, basta rodar os seguintes comandos: 

```
rm -R data
sudo docker-compose up
```

- Por fim, será possível anexar a planilha e registrar todos os equipamentos de uma única vez. 

## Lista de controle:
- [X] Meu código segue a folha de estilos implementada
- [X] Meu commits segue a política de commits do repositório.
- [X] Minhas modificações requerem modificações na documentação atual.
- [] Atualizei a Documentação
- [] Adicionei testes para cobrir minhas modificações.
- [] Todos os testes foram aprovados.

2023-07-04 22:09 UTC, AlineLermen reviewed
Se a planilha estiver vazia, com zero linhas de equipamentos e etc, o botão `Registrar` apenas não funciona. A modal não é fechada, e não aparece erros informando da situação da planilha

2023-07-04 22:09 UTC, AlineLermen approved these changes

2023-07-05 18:03 UTC, JPedroCh requested changes
Quando tem algum erro na formatação dos dados não é apresentado para o usuário, somente no console. Ex:
<img width="316" alt="image" src="https://github.com/fga-eps-mds/2023-1-Alectrion-FrontEnd/assets/48698461/df3be5e5-c1d0-4a84-b61a-d2809be211df">

2023-07-05 20:25 UTC, JPedroCh approved these changes

2023-07-05 21:31 UTC, merged